# Colores oscuros
COLOR_DE_FONDO_DARK = "#3b2f2f"
COLOR_DE_TEXTO_DARK = "#eae0d5"
COLOR_BOTONES_ESPECIALES_DARK = "#a67c52"
COLOR_BOTONES_DARK = "#4e3d3d"
COLOR_CAJA_TEXTO_DARK = "#3b2f2f"

# Colores claros
COLOR_DE_FONDO_LIGHT = "#f5f5dc"
COLOR_DE_TEXTO_LIGHT = "#5c4033"
COLOR_BOTONES_ESPECIALES_LIGHT = "#d2b48c"
COLOR_BOTONES_LIGHT = "#e3d6c6"
COLOR_CAJA_TEXTO_LIGHT = "#f5f5dc"
